server {
  listen 80;
  server_name localhost;

  # Serve env.js correctly
  location = /config/env.js {
    root /usr/share/nginx/html;
    add_header Content-Type application/javascript;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
}