apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soccerize-backend-ingress
  namespace: soccerize-app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: soccerize
    alb.ingress.kubernetes.io/subnets: subnet-0ab41c3ea203ba7e1,subnet-07e1f616b1024991c
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: backend-node-svc
                port:
                  number: 5000
