apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soccerize-frontend-ingress
  namespace: soccerize-app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: soccerize
    alb.ingress.kubernetes.io/group.order: "1"
    alb.ingress.kubernetes.io/subnets: subnet-04560c24b54c1baa2,subnet-070f7567f83a21664
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /config/
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
