apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-node
  namespace: soccerize-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-node
  template:
    metadata:
      labels:
        app: backend-node
    spec:
      containers:
        - name: backend-node
          image: erysimum/soccerize-backend-node:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-node-env
                  key: TABLE_NAME
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-node-env
                  key: SQS_QUEUE_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: "us-east-1"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
