apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: soccer
  region: us-east-1

managedNodeGroups:
  - name: soccer-ng
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    volumeSize: 20
    privateNetworking: true
    subnets:
      - subnet-05a5f9fc1c7c37917
      - subnet-0bb8732feaa1cb0d7
    ssh:
      allow: true
      publicKeyName: terra-key
    updateConfig:
      maxUnavailable: 1
